### ISSUE TITLE
Things to do before we merge the current dev into master

### ISSUE THREAD

**Issue by zoltuz** [BuildACell/BioCRNPyler#128]
This is a placeholder issue to collect all that needs to be done before we merge dev into master.
Feel free to add items to the list!

- [X] DNA Construct PR (Andrey #102 )
- [X] DNA construct numpy/matplotlib bug #146 
- [x] refactor the SBML interface, see #122 (Ayush PR)
- [x] test MAK and other non-massaction kinetic types via bioscrape (Ayush PR)
- [x] test MAK and other non-massaction kinetic types via libroadrunner (Ayush PR)
- [x] test MAK and other non-massaction kinetic types via Copasi [@zoltuz] (Ayush PR)
- [x] test stochastic MAK simulation via bioscrape  (Ayush PR)
- [X] update version information for biocrnpyler (Version 1.0.0!) #140 
- [x] Add copying for Components placed into Mixtures and appropriate getters to retrieve internal Components. see #123 (William PR)
- [X] Add copying for Species & Reactions placed into CRNs and appropriate getters to retrieve internal Species. This step should simultaneously ensure that duplicate species are merged. see #120 (William CRN PR TODO)
- [X] Add jupyter documentation to Scope (above two changes). (William CRN PR TODO)
- [X] Add jupyter documentation and more unit tests to OrderedPolymerSpecies class. In particular documentation & tests of how this class interacts with ComplexSpecies vs Reactions is crucial (William CRN PR TODO)
- [x] Add jupyter documentation to viewing found / search parameters used in CRN compilation (William PR)
- [X] create Contributing.md see #107 (Zoltan)
- [X] edit README.md, welcome message, how to install, where to start (William & Zoltan)
- [X] register the package at PyPi and upload it (create a git tag and package with matching version number) (Ayush + Zoltan)
- [x] Create SBtools Developer Mailing List for BioCRNpyler (Ayush)
- [X] Add more backwards compatibility for old propensity interface. Currently, only Massaction is supported. (Zoltan in #141 )
- [x] Hoverboxes over reaction lines in plotting are no longer displaying anything. (Andrey)
- [X] get rid of all parameter warnings. These are no longer necessary now that parameters can be displayed with pretty_print. (William PR #134 )
- [X] Update Wiki /README (Zoltan)
- [X] Read the Docs! (Ayush) ZAT: Richard set up the webhook for us. 
- [x] [Binder Example Notebooks](https://notebooks.gesis.org/binder/jupyter/user/buildacell-biocrnpyler-8l6pkzvw/tree/examples) (Andrey)
- [x] Github/BioCRNpyler.io Intro Page (William)
- [x] Mini Presentation (William)
- [x] Get some testing from SBtools users once PIP install is available
- [x] Paper Main Text Edits (William)
- [x] Paper Table of Classes/Functionality (All of us!)
- [x] Figure 1: Overview (William)
- [x] Figure 2: Compilation (William)
- [x] Figure 4: DNA_construct (Andrey)

**Comment by ayush9pandey** [comment]
Do we also want it to be pip installable when we merge to master or is that for later?

**Comment by ayush9pandey** [comment]
and what about this: 
![image](https://user-images.githubusercontent.com/8139195/88426130-784f9200-cda5-11ea-9c18-28d5b65f95a1.png)

**Comment by WilliamIX** [comment]
@ayush9pandey we want to do this all by IWBDA - especially PIP installation. I also talked to Richard about this and he suggests we create a listerv for developers and use that email address for PIP.

@zoltuz I don't think we should rename propensity parameters because the names you suggest are used for some specific enzyme models but are by no means universal. The names we have used are more typical forms used for hill functions in general, with reference to a specific kind of model like enzyme kinetics.

**Comment by zoltuz** [comment]
> Do we also want it to be pip installable when we merge to master or is that for later?

Manually yes! Automatically, probably later

**Comment by zoltuz** [comment]
> and what about this:
> ![image](https://user-images.githubusercontent.com/8139195/88426130-784f9200-cda5-11ea-9c18-28d5b65f95a1.png)

good catch! We need to set up a git tag when we merge to master (ideally with the same version number as we will have in the setup.py)

**Comment by ayush9pandey** [comment]
Also what about documentation with sphinx ?

**Comment by WilliamIX** [comment]
> Also what about documentation with sphinx ?

I recently converted most comments to the """ COMMENT """ after a class/function definition so this should get something. Things like keywords, arguments, etc are not necessarily documented though.

**Comment by ayush9pandey** [comment]
> 
> 
> > Also what about documentation with sphinx ?
> 
> I recently converted most comments to the """ COMMENT """ after a class/function definition so this should get something. Things like keywords, arguments, etc are not necessarily documented though.

I meant more about setting up : https://biocrnpyler.readthedocs.io/en/latest/

**Comment by WilliamIX** [comment]
> I meant more about setting up : https://biocrnpyler.readthedocs.io/en/latest/

It would be awesome if you could do this!

**Comment by zoltuz** [comment]
> > I meant more about setting up : https://biocrnpyler.readthedocs.io/en/latest/
> 
> It would be awesome if you could do this!

A bit of editing is needed to generate useful documentation. But the most important part is the webhook, which triggers the build for the documentation after each commit.

To do so, someone with admin rights on this repo needs to do this:
https://docs.readthedocs.io/en/stable/webhooks.html#github
This is our webhook:
readthedocs.org/api/v2/webhook/biocrnpyler/119366/

**Comment by zoltuz** [comment]
For the GitHub page, we need someone with admins right on this repo:
https://guides.github.com/features/pages/
@ayush9pandey Can you ask for a promotion? :)

**Comment by murrayrm** [comment]
For the various accounts that we are setting up (readthedocs, etc): can people add me as an admin on those as well?  I can set them up if that's easier.

**Comment by zoltuz** [comment]
@murrayrm sure, I've added you as an admin for the readthedocs, the other accounts (Travis and codecov) run through GitHub authentication, so you have admin access to those tools. I think that's all the tools we have, for now.  I'll keep in mind to add you as an admin for any future tool that we use. 

In the meantime, can you enable GitHub pages for this repo? 
https://guides.github.com/features/pages/

and add this webhook to this repo:
https://docs.readthedocs.io/en/stable/webhooks.html#github
This is our webhook:
readthedocs.org/api/v2/webhook/biocrnpyler/119366/

Many thanks!

**Comment by murrayrm** [comment]
@zoltuz Done.  For GitHub pages, I told it to look in the docs/ folder of the master branch (the other choice was the main folder).  

Let me know if you need changes to the configuration.

**Comment by dr3y** [comment]
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/BuildACell/BioCRNPyler/dev?filepath=%2Fexamples%2F)

**Comment by dr3y** [comment]
I'm confused about the "Hoverboxes over reaction lines aren't displaying anything" Hovering over the lines never displayed anything. Hovering over the boxes displays a bunch of stuff though.
![image](https://user-images.githubusercontent.com/3620565/89090041-3f8b5c00-d355-11ea-9028-300d504c22e1.png)

**Comment by WilliamIX** [comment]
My mistake - I thought that the lines displayed things too!

**Comment by dr3y** [comment]
added binder badge with PR #162

**Comment by zoltuz** [comment]
All done, thanks for the teamwork!
